version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: traffic-weather-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: skdnjsqls
      MYSQL_DATABASE: traffic_weather_db
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: